const REPO_OWNER = "rregis2022";
const REPO_NAME = "k6-loadtesting-reports";

const REPORT_BASE_URL =
`https://raw.githubusercontent.com/${REPO_OWNER}/${REPO_NAME}/staging/reports/`;


/*
* Load the report index generated by Repo 1
*/
async function loadReportIndex() {

const response = await fetch(
`${REPORT_BASE_URL}index.json?cache=${Date.now()}`
);

if (!response.ok) {
throw new Error("Unable to load report index.");
}

return await response.json();
}


/*
* Load an individual k6 report
*/
async function loadReport(filename) {

const response = await fetch(
`${REPORT_BASE_URL}${encodeURIComponent(filename)}?cache=${Date.now()}`
);

if (!response.ok) {
throw new Error(`Unable to load report: ${filename}`);
}

return await response.json();
}


/*
* Extract metrics from the k6 summary JSON
*/
function extractMetrics(report) {

const metrics = report.metrics || {};

const duration = metrics.http_req_duration || {};
const requests = metrics.http_reqs || {};
const failed = metrics.http_req_failed || {};
const vus = metrics.vus || {};
const iterations = metrics.iterations || {};
const checks = metrics.checks || {};
const received = metrics.data_received || {};
const sent = metrics.data_sent || {};

return {

vus: vus.value ?? 0,

requests: requests.count ?? 0,

requestRate: requests.rate ?? 0,

average: duration.avg ?? 0,

median: duration.med ?? 0,

p90: duration["p(90)"] ?? 0,

p95: duration["p(95)"] ?? 0,

max: duration.max ?? 0,

failureRate: failed.value ?? 0,

checksPassed: checks.passes ?? 0,

checksFailed: checks.fails ?? 0,

iterations: iterations.count ?? 0,

dataReceived: received.count ?? 0,

dataSent: sent.count ?? 0
};
}


/*
* Format numbers
*/
function formatNumber(value) {

return Number(value).toLocaleString(
undefined,
{
maximumFractionDigits: 2
}
);
}


/*
* Format milliseconds
*/
function formatMs(value) {

return `${Number(value).toFixed(2)} ms`;
}


/*
* Format percentage
*/
function formatPercentage(value) {

return `${(Number(value) * 100).toFixed(2)}%`;
}


/*
* Display the selected report
*/
function displayReport(filename, report) {

const metrics = extractMetrics(report);

const container =
document.getElementById("reportDetails");

if (!container) {
console.error("reportDetails element not found.");
return;
}


const totalChecks =
metrics.checksPassed + metrics.checksFailed;


container.innerHTML = `

<div class="report-header">

<h2>Performance Test Results</h2>

<p>
<strong>Report:</strong>
${filename}
</p>

</div>


<h3>Key Performance Metrics</h3>


<div class="metrics-grid">


<div class="metric-card">

<h3>Virtual Users</h3>

<div class="metric-value">
${metrics.vus}
</div>

</div>


<div class="metric-card">

<h3>HTTP Requests</h3>

<div class="metric-value">
${formatNumber(metrics.requests)}
</div>

</div>


<div class="metric-card">

<h3>Throughput</h3>

<div class="metric-value">
${metrics.requestRate.toFixed(2)}
<span class="metric-unit">req/s</span>
</div>

</div>


<div class="metric-card">

<h3>Average Response Time</h3>

<div class="metric-value">
${formatMs(metrics.average)}
</div>

</div>


<div class="metric-card">

<h3>P95 Response Time</h3>

<div class="metric-value">
${formatMs(metrics.p95)}
</div>

</div>


<div class="metric-card">

<h3>Maximum Response Time</h3>

<div class="metric-value">
${formatMs(metrics.max)}
</div>

</div>


<div class="metric-card">

<h3>HTTP Failure Rate</h3>

<div class="metric-value">
${formatPercentage(metrics.failureRate)}
</div>

</div>


<div class="metric-card">

<h3>Iterations</h3>

<div class="metric-value">
${formatNumber(metrics.iterations)}
</div>

</div>


<div class="metric-card">

<h3>Checks</h3>

<div class="metric-value">

${formatNumber(metrics.checksPassed)}
/
${formatNumber(totalChecks)}

</div>

</div>

</div>


<h3>Performance Test Details</h3>


<table class="details-table">

<tbody>

<tr>
<td>Median Response Time</td>
<td>${formatMs(metrics.median)}</td>
</tr>

<tr>
<td>P90 Response Time</td>
<td>${formatMs(metrics.p90)}</td>
</tr>

<tr>
<td>Data Received</td>
<td>${formatNumber(metrics.dataReceived)} bytes</td>
</tr>

<tr>
<td>Data Sent</td>
<td>${formatNumber(metrics.dataSent)} bytes</td>
</tr>

<tr>
<td>Checks Passed</td>
<td>${formatNumber(metrics.checksPassed)}</td>
</tr>

<tr>
<td>Checks Failed</td>
<td>${formatNumber(metrics.checksFailed)}</td>
</tr>

</tbody>

</table>

`;
}


/*
* Populate the report selector
*/
function displayReportList(filenames) {

const selector =
document.getElementById("reportSelector");

if (!selector) {
return;
}

selector.innerHTML = "";

filenames.forEach(filename => {

const option =
document.createElement("option");

option.value = filename;
option.textContent = filename;

selector.appendChild(option);

});
}


/*
* Initialize dashboard
*/
async function initializeDashboard() {

const status =
document.getElementById("status");

try {

status.textContent =
"Loading k6 reports...";


const index =
await loadReportIndex();


if (!index.reports ||
index.reports.length === 0) {

status.textContent =
"No k6 reports are currently available.";

return;
}


displayReportList(index.reports);


const firstReport =
index.reports[0];


const report =
await loadReport(firstReport);


displayReport(
firstReport,
report
);


const selector =
document.getElementById("reportSelector");


selector.addEventListener(
"change",
async event => {

const filename =
event.target.value;

status.textContent =
`Loading ${filename}...`;

try {

const report =
await loadReport(filename);


displayReport(
filename,
report
);


status.textContent =
"Report loaded successfully.";

} catch (error) {

console.error(error);

status.textContent =
"Unable to load selected report.";

}

}
);


status.textContent =
`${index.reports.length} report(s) available.`;

} catch (error) {

console.error(error);


status.textContent =
"Unable to load k6 reports.";


const container =
document.getElementById("reportDetails");


if (container) {

container.innerHTML = `

<p class="error-message">

<strong>Error:</strong>
${error.message}

</p>

`;

}

}
}


document.addEventListener(
"DOMContentLoaded",
initializeDashboard
);